ignore:
  - "tests"
  - "benches"
  - "examples"
  - "projects/dxt-lossless-transform-cli"

comment:
  layout: "reach, diff, flags, files"
  require_changes: true

github_checks:
  annotations: false

coverage:
  status:
    project:
      default:
        threshold: 5%
