name: Test, Coverage, Release on Tag

on:
  push:
    branches: [ main ]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'projects/**'
      - 'fuzz/**'
      - 'assets/tests/**'
      - '.github/workflows/rust.yml'
    tags:
      - '*'
  pull_request:
    branches: [ main ]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'projects/**'
      - 'fuzz/**'
      - 'assets/tests/**'
      - '.github/workflows/rust.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  build-with-pgo: true

jobs:
  test:
    strategy:
      matrix:
        include:
          # Linux All features (nightly)
          - { label: "Linux x64 (All Features, Nightly)", os: ubuntu-latest, target: x86_64-unknown-linux-gnu, use-cross: false, additional-test-args: "--all-features", rust-toolchain: 'nightly' }
          - { label: "Linux x86 (All Features, Nightly)", os: ubuntu-latest, target: i686-unknown-linux-gnu, use-cross: false, additional-test-args: "--all-features", rust-toolchain: 'nightly' }
          
          # Linux No features (stable)
          - { label: "Linux x64 (Stable)", os: ubuntu-latest, target: x86_64-unknown-linux-gnu, use-cross: false, rust-toolchain: 'stable' }
          - { label: "Linux x86 (Stable)", os: ubuntu-latest, target: i686-unknown-linux-gnu, use-cross: false, rust-toolchain: 'stable' }
          
          # No CPU detection (on x86)
          - { label: "Linux x64 (No CPU Detection)", os: ubuntu-latest, target: x86_64-unknown-linux-gnu, use-cross: false, features: "no-runtime-cpu-detection", rust-toolchain: 'stable' }
          - { label: "Linux x86 (No CPU Detection)", os: ubuntu-latest, target: i686-unknown-linux-gnu, use-cross: false, features: "no-runtime-cpu-detection", rust-toolchain: 'stable' }
          
          # 32-bit ARM (e.g. Raspberry Pi, Legacy Android)
          - { label: "Linux 32-bit ARMv7", os: ubuntu-latest, target: armv7-unknown-linux-gnueabihf, use-cross: true, rust-toolchain: 'stable' }
          
          # 64-bit ARM (e.g. Raspberry Pi 4+, Modern ARM servers)
          - { label: "Linux 64-bit ARM64", os: ubuntu-latest, target: aarch64-unknown-linux-gnu, use-cross: true, rust-toolchain: 'stable' }

          # Big Endian (32-bit)
          - { label: "Linux + Big Endian 32-bit", os: ubuntu-latest, target: powerpc-unknown-linux-gnu, use-cross: true, rust-toolchain: 'stable', no-default-features: true }
          
          # Big Endian (64-bit)
          - { label: "Linux + Big Endian 64-bit", os: ubuntu-latest, target: powerpc64-unknown-linux-gnu, use-cross: true, rust-toolchain: 'stable' }

          # Windows
          - { label: "Windows x64", os: windows-latest, target: x86_64-pc-windows-msvc, use-cross: false, rust-toolchain: 'stable' }
          - { label: "Windows x86", os: windows-latest, target: i686-pc-windows-msvc, use-cross: false, rust-toolchain: 'stable' }
          
          # macOS
          - { label: "macOS Intel", os: macos-13, target: x86_64-apple-darwin, use-cross: false, rust-toolchain: 'stable' }
          - { label: "macOS Apple Silicon", os: macos-14, target: aarch64-apple-darwin, use-cross: false, rust-toolchain: 'stable' }

          # Android (Mobile)
          - { label: "Android ARM64", os: ubuntu-latest, target: aarch64-linux-android, use-cross: true, additional-test-args: "--all-features", rust-toolchain: 'nightly' }
          - { label: "Android ARM v7", os: ubuntu-latest, target: armv7-linux-androideabi, use-cross: true, additional-test-args: "--all-features", rust-toolchain: 'nightly' }
          # - { label: "Android x64", os: ubuntu-latest, target: x86_64-linux-android, use-cross: true, additional-test-args: "--all-features", rust-toolchain: 'nightly' }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        uses: Reloaded-Project/devops-rust-test-and-coverage@v1
        with:
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          features: ${{ matrix.features }}
          rust-toolchain: ${{ matrix.rust-toolchain }}
          additional-test-args: ${{ matrix.additional-test-args }}
          no-default-features: ${{ matrix.no-default-features }} # Build fails for powerpc-unknown-linux-gnu due to no U64 atomics in CLI. So we feature gate it.

      # Uncomment after first release.
      # - name: Check semver
      #   uses: obi1kenobi/cargo-semver-checks-action@v2

  debug-endian-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      # Install Rust toolchain and dependencies needed for the project
      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false

      - name: Setup Rust Caching
        uses: Swatinem/rust-cache@v2
        with:
          key: claude-rust-cache
          cache-on-failure: true
          cache-all-crates: true

      - name: Install cross
        shell: bash
        run: RUSTFLAGS="" cargo install cross --git https://github.com/cross-rs/cross

      - name: Validate Cross-Endian Transformations
        run: cargo run --bin dxt-lossless-transform-cli --features debug-endian -- debug-endian

  build-cli:
    strategy:
      matrix:
        include:
          # Linux Targets
          - { label: "Build CLI Linux x64", os: ubuntu-latest, target: x86_64-unknown-linux-gnu, use-cross: false }
          - { label: "Build CLI Linux x86", os: ubuntu-latest, target: i686-unknown-linux-gnu, use-cross: false }
          - { label: "Build CLI Linux ARM64", os: ubuntu-latest, target: aarch64-unknown-linux-gnu, use-cross: true }
          
          # Windows Targets
          - { label: "Build CLI Windows x64", os: windows-latest, target: x86_64-pc-windows-msvc, use-cross: false }
          - { label: "Build CLI Windows x86", os: windows-latest, target: i686-pc-windows-msvc, use-cross: false }
          
          # macOS Targets
          - { label: "Build CLI macOS Intel", os: macos-13, target: x86_64-apple-darwin, use-cross: false }
          - { label: "Build CLI macOS Apple Silicon", os: macos-14, target: aarch64-apple-darwin, use-cross: false }

          # Android
          - { label: "Build CLI Android ARM64", os: ubuntu-latest, target: aarch64-linux-android, use-cross: true }
          - { label: "Build CLI Android ARM v7", os: ubuntu-latest, target: armv7-linux-androideabi, use-cross: true }
          - { label: "Build CLI Android x64", os: ubuntu-latest, target: x86_64-linux-android, use-cross: true }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build CLI
        uses: Reloaded-Project/devops-rust-lightweight-binary@v1
        with:
          crate-name: "dxt-lossless-transform-cli"
          rust-project-path: "projects/tools/dxt-lossless-transform-cli"
          workspace-path: "."
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          additional-rustc-args: "--all-features"
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  build-c-libraries:
    strategy:
      matrix:
        include:
          # Linux Targets
          - { label: "Build C API Linux x64", os: ubuntu-latest, target: x86_64-unknown-linux-gnu, use-cross: false }
          - { label: "Build C API Linux x86", os: ubuntu-latest, target: i686-unknown-linux-gnu, use-cross: false }
          - { label: "Build C API Linux ARM64", os: ubuntu-latest, target: aarch64-unknown-linux-gnu, use-cross: true }
          
          # Windows Targets
          - { label: "Build C API Windows x64", os: windows-latest, target: x86_64-pc-windows-msvc, use-cross: false }
          - { label: "Build C API Windows x86", os: windows-latest, target: i686-pc-windows-msvc, use-cross: false }
          
          # macOS Targets
          - { label: "Build C API macOS Intel", os: macos-13, target: x86_64-apple-darwin, use-cross: false }
          - { label: "Build C API macOS Apple Silicon", os: macos-14, target: aarch64-apple-darwin, use-cross: false }

          # Android
          - { label: "Build C API Android ARM64", os: ubuntu-latest, target: aarch64-linux-android, use-cross: true }
          - { label: "Build C API Android ARM v7", os: ubuntu-latest, target: armv7-linux-androideabi, use-cross: true }
          - { label: "Build C API Android x64", os: ubuntu-latest, target: x86_64-linux-android, use-cross: true }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build C API (DDS)
        uses: Reloaded-Project/devops-rust-lightweight-binary@v1
        with:
          crate-name: "dxt-lossless-transform-dds"
          rust-project-path: "projects/extensions/file-formats/dxt-lossless-transform-dds"
          workspace-path: "."
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          features: "c-exports"
          additional-rustc-args: "--all-features"
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          use-cache: true
          build-library: true

      - name: Build C API (Common)
        uses: Reloaded-Project/devops-rust-lightweight-binary@v1
        with:
          crate-name: "dxt-lossless-transform-api-common"
          rust-project-path: "projects/api/dxt-lossless-transform-api-common"
          workspace-path: "."
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          features: "c-exports"
          additional-rustc-args: "--all-features"
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          use-cache: false # Cache setup is inherited from first call.
          build-library: true

      - name: Build C API (BC1)
        uses: Reloaded-Project/devops-rust-lightweight-binary@v1
        with:
          crate-name: "dxt-lossless-transform-bc1-api"
          rust-project-path: "projects/api/dxt-lossless-transform-bc1-api"
          workspace-path: "."
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          features: "c-exports"
          additional-rustc-args: "--all-features"
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          use-cache: false # Cache setup is inherited from first call.
          build-library: true

      - name: Build C API (BC1 Core)
        uses: Reloaded-Project/devops-rust-lightweight-binary@v1
        with:
          crate-name: "dxt-lossless-transform-bc1"
          rust-project-path: "projects/core/dxt-lossless-transform-bc1"
          workspace-path: "."
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          features: "c-exports"
          additional-rustc-args: "--all-features"
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          use-cache: false # Cache setup is inherited from first call.
          build-library: true

      - name: Build C API (LTU)
        uses: Reloaded-Project/devops-rust-lightweight-binary@v1
        with:
          crate-name: "dxt-lossless-transform-ltu"
          rust-project-path: "projects/extensions/estimators/dxt-lossless-transform-ltu"
          workspace-path: "."
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          features: "c-exports"
          additional-rustc-args: "--all-features"
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          use-cache: false # Cache setup is inherited from first call.
          build-library: true

  build-c-cpp-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: C bindings - API Common
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/api/dxt-lossless-transform-api-common/'
          config-file: ../../../cbindgen_c.toml
          output-header-file: dxt-lossless-transform-api-common.h
          artifact-prefix: ""
          use-cache: true

      - name: C++ bindings - API Common
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/api/dxt-lossless-transform-api-common/'
          config-file: ../../../cbindgen_cpp.toml
          output-header-file: dxt-lossless-transform-api-common.hpp
          artifact-prefix: ""
          use-cache: false # Cache setup is inherited from first call.

      - name: C bindings - DDS
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/extensions/file-formats/dxt-lossless-transform-dds/'
          config-file: ../../../../cbindgen_c.toml
          output-header-file: dxt-lossless-transform-dds.h
          artifact-prefix: ""
          use-cache: false # Cache setup is inherited from first call.

      - name: C++ bindings - DDS
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/extensions/file-formats/dxt-lossless-transform-dds/'
          config-file: ../../../../cbindgen_cpp.toml
          output-header-file: dxt-lossless-transform-dds.hpp
          artifact-prefix: ""
          use-cache: false

      - name: C bindings - BC1 API
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/api/dxt-lossless-transform-bc1-api/'
          config-file: ../../../cbindgen_c.toml
          output-header-file: dxt-lossless-transform-bc1-api.h
          artifact-prefix: ""
          use-cache: false # Cache setup is inherited from first call.

      - name: C++ bindings - BC1 API
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/api/dxt-lossless-transform-bc1-api/'
          config-file: ../../../cbindgen_cpp.toml
          output-header-file: dxt-lossless-transform-bc1-api.hpp
          artifact-prefix: ""
          use-cache: false # Cache setup is inherited from first call.

      - name: C bindings - BC1 Core
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/core/dxt-lossless-transform-bc1/'
          config-file: ../../../cbindgen_c.toml
          output-header-file: dxt-lossless-transform-bc1.h
          artifact-prefix: ""
          use-cache: false # Cache setup is inherited from first call.

      - name: C++ bindings - BC1 Core
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/core/dxt-lossless-transform-bc1/'
          config-file: ../../../cbindgen_cpp.toml
          output-header-file: dxt-lossless-transform-bc1.hpp
          artifact-prefix: ""
          use-cache: false # Cache setup is inherited from first call.

      - name: C bindings - LTU
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/extensions/estimators/dxt-lossless-transform-ltu/'
          config-file: ../../../../cbindgen_c.toml
          output-header-file: dxt-lossless-transform-ltu.h
          artifact-prefix: ""
          use-cache: false # Cache setup is inherited from first call.

      - name: C++ bindings - LTU
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/extensions/estimators/dxt-lossless-transform-ltu/'
          config-file: ../../../../cbindgen_cpp.toml
          output-header-file: dxt-lossless-transform-ltu.hpp
          artifact-prefix: ""
          use-cache: false # Cache setup is inherited from first call.

  publish-crate:
    permissions:
      contents: write

    needs: [test, debug-endian-validation, build-cli, build-c-libraries, build-c-cpp-headers]
    # Publish only on tags
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Publish Rust Crate and Artifacts  
        uses: Reloaded-Project/devops-publish-action@v1
        with:
          crates-io-token: ${{ secrets.CRATES_IO_TOKEN }}
          rust-project-paths: |
            .