name: Test, Upload Coverage and Release Rust

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:


env:
  build-with-pgo: true

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          # Common Linux Targets
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, use-cross: false }
          - { os: ubuntu-latest, target: i686-unknown-linux-gnu, use-cross: false }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-gnu, use-cross: true }
          - { os: ubuntu-latest, target: armv7-unknown-linux-gnueabihf, use-cross: true }
          # Common Windows Targets
          - { os: windows-latest, target: x86_64-pc-windows-msvc, use-cross: false }
          - { os: windows-latest, target: i686-pc-windows-msvc, use-cross: false }
          # - { os: windows-latest, target: aarch64-pc-windows-msvc, use-cross: true }
          # Common Apple Targets
          - { os: macos-13, target: x86_64-apple-darwin, use-cross: false }
          - { os: macos-14, target: aarch64-apple-darwin, use-cross: false }
          # Big Endian (64-bit)
          - { os: ubuntu-latest, target: powerpc64-unknown-linux-gnu, use-cross: true }
          # Big Endian (32-bit)
          - { os: ubuntu-latest, target: powerpc-unknown-linux-gnu, use-cross: true }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        uses: Reloaded-Project/devops-rust-test-and-coverage@v1
        with:
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build CLI
        uses: Reloaded-Project/devops-rust-lightweight-binary@v1
        with:
          crate-name: "dxt-lossless-transform-cli"
          rust-project-path: "projects/dxt-lossless-transform-cli"
          workspace-path: "."
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build C API
        uses: Reloaded-Project/devops-rust-lightweight-binary@v1
        with:
          crate-name: "dxt-lossless-transform-api"
          rust-project-path: "projects/dxt-lossless-transform-api"
          workspace-path: "."
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          features: "c-exports"
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2

  build-c-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Generate C++ bindings
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/dxt-lossless-transform-api/'
          config-file: cbindgen_cpp.toml
          output-header-file: bindings_cpp.hpp
      - name: Generate C bindings
        uses: Reloaded-Project/devops-rust-cbindgen@v1
        with:
          rust-project-path: 'projects/dxt-lossless-transform-api/'
          config-file: cbindgen_c.toml
          output-header-file: bindings_c.h

  publish-crate:
    permissions:
      contents: write

    needs: [build-and-test]
    # Publish only on tags
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Publish Rust Crate and Artifacts  
        uses: Reloaded-Project/devops-publish-action@v1
        with:
          crates-io-token: ${{ secrets.CRATES_IO_TOKEN }}
          rust-project-paths: |
            .