name: Test, Upload Coverage and Release Rust

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:


env:
  build-with-pgo: true

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          # Common Linux Targets
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, use-cross: false }
          - { os: ubuntu-latest, target: i686-unknown-linux-gnu, use-cross: false }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-gnu, use-cross: true }
          - { os: ubuntu-latest, target: armv7-unknown-linux-gnueabihf, use-cross: true }
          # Common Windows Targets
          - { os: windows-latest, target: x86_64-pc-windows-msvc, use-cross: false }
          - { os: windows-latest, target: i686-pc-windows-msvc, use-cross: false }
          # - { os: windows-latest, target: aarch64-pc-windows-msvc, use-cross: true }
          # Common Apple Targets
          - { os: macos-13, target: x86_64-apple-darwin, use-cross: false }
          - { os: macos-14, target: aarch64-apple-darwin, use-cross: false }
          # Big Endian (64-bit)
          - { os: ubuntu-latest, target: powerpc64-unknown-linux-gnu, use-cross: true }
          # Big Endian (32-bit)
          - { os: ubuntu-latest, target: powerpc-unknown-linux-gnu, use-cross: true }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        uses: Reloaded-Project/devops-rust-test-and-coverage@v1
        with:
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
      # Note: The GitHub Runner Images will contain an up to date Rust Stable Toolchain
      #       thus as per recommendation of cargo-semver-checks, we're using stable here.
      #
      # Note to reader. If adding this to a new repo, please clear cache.
      - name: Run cargo-semver-checks
        if: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          SEARCH_RESULT=$(cargo search "^dxt-lossless-transform$" --limit 1)

          if echo "$SEARCH_RESULT" | grep -q "^dxt-lossless-transform "; then
            rustup target add ${{ matrix.target }}
            cargo install cargo-semver-checks
            cargo semver-checks --target ${{ matrix.target }} --features c-exports
          else
              echo "No previous version found on crates.io. Skipping semver checks."
          fi

  publish-crate:
    permissions:
      contents: write

    needs: [build-and-test]
    # Publish only on tags
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Publish Rust Crate and Artifacts  
        uses: Reloaded-Project/devops-publish-action@v1
        with:
          crates-io-token: ${{ secrets.CRATES_IO_TOKEN }}
          rust-project-paths: |
            .